// premium_work/components/SectorsAccordion.tsx
"use client";

import { ArrowRight, ChevronDown } from "lucide-react";
import { useState } from "react";

const sectors = [
  {
    title: "Hoteles",
    slug: "hoteles",
    copy: "Camareros, maîtres, hostess y personal de housekeeping seleccionados y supervisados para el día a día del hotel y sus eventos.",
  },
  {
    title: "Restaurantes",
    slug: "restaurantes",
    copy: "Refuerzos de sala y cocina que se integran con agilidad en tu equipo, trabajando con los estándares de tu casa.",
  },
  {
    title: "Catering",
    slug: "catering",
    copy: "Equipos completos de sala, cocina y office para servicios dentro y fuera de tus instalaciones.",
  },
  {
    title: "Eventos corporativos",
    slug: "eventos-corporativos",
    copy: "Personal de recepción, sala y coordinación para congresos, convenciones y actos de empresa.",
  },
  {
    title: "Eventos deportivos",
    slug: "eventos-deportivos",
    copy: "Equipos ágiles para hospitality, palcos y zonas VIP en competiciones y torneos.",
  },
  {
    title: "Festivales",
    slug: "festivales",
    copy: "Refuerzos numerosos y supervisados para barras, accesos y zonas de restauración.",
  },
  {
    title: "Bodas y celebraciones",
    slug: "bodas-y-celebraciones",
    copy: "Maîtres, camareros y hostess con la presencia y el cuidado que exige un día único.",
  },
  {
    title: "Eventos privados",
    slug: "experiencias-privadas",
    copy: "Discreción y excelencia para celebraciones privadas, con un solo interlocutor.",
  },
];

export function SectorsAccordion() {
  const [open, setOpen] = useState<number | null>(0);

  return (
    <section aria-label="Sectores en los que trabajamos" className="relative overflow-hidden bg-white py-10 md:py-16">
      <div aria-hidden="true" className="hero-dots pointer-events-none absolute inset-0" />
      <div className="relative z-10 mx-auto grid w-full max-w-[1600px] gap-6 px-5 md:gap-12 md:px-8 lg:grid-cols-[1fr_1.5fr] lg:gap-24 lg:px-10">
        <div className="lg:sticky lg:top-28 lg:self-start">
          <p className="eyebrow flex items-center gap-2 text-[#131313]/60">
            <span className="text-[#eab308]" aria-hidden="true">◆</span> Sectores
          </p>
          <h2 className="display mt-4 text-3xl leading-[1.02] text-[#131313] md:mt-6 md:text-[clamp(2.5rem,5vw,4.5rem)]">
            ¿Dónde<br />trabajamos?
          </h2>
          <p className="mt-6 hidden max-w-md text-base leading-7 text-[#131313]/70 md:block">
            Llevamos profesionales seleccionados, formados y supervisados a cada tipo de espacio y evento.
          </p>
          <a
            href="/solicitar-servicio"
            className="mt-6 inline-flex items-center gap-2 rounded-full bg-[#2451e6] px-6 py-3.5 text-sm font-bold text-white transition hover:-translate-y-0.5 hover:bg-[#1b45c4] md:mt-8"
          >
            Solicitar servicio <ArrowRight size={18} aria-hidden="true" />
          </a>
        </div>

        <div className="border-t border-[#131313]/15">
          {sectors.map((sector, index) => {
            const isOpen = open === index;
            return (
              <div key={sector.slug} className="border-b border-[#131313]/15">
                <button
                  type="button"
                  aria-expanded={isOpen}
                  aria-controls={`sector-panel-${sector.slug}`}
                  onClick={() => setOpen(isOpen ? null : index)}
                  className="group flex w-full items-center justify-between gap-6 py-3 text-left md:py-4"
                >
                  <span className={`display text-xl transition-colors md:text-[1.75rem] ${isOpen ? "text-[#173aab]" : "text-[#131313] group-hover:text-[#173aab]"}`}>
                    {sector.title}
                  </span>
                  <span className={`flex size-9 shrink-0 items-center justify-center rounded-full border transition-all md:size-10 ${isOpen ? "rotate-180 border-[#2451e6] bg-[#2451e6] text-white" : "border-[#131313]/25 text-[#131313]/70 group-hover:border-[#173aab]/60"}`}>
                    <ChevronDown size={20} aria-hidden="true" />
                  </span>
                </button>
                <div
                  id={`sector-panel-${sector.slug}`}
                  role="region"
                  className={`grid transition-[grid-template-rows] duration-300 ease-out ${isOpen ? "[grid-template-rows:1fr]" : "[grid-template-rows:0fr]"}`}
                >
                  <div className="overflow-hidden">
                    <div className="pb-7 pr-4 md:pr-16">
                      <p className="max-w-xl text-base leading-7 text-[#131313]/70">{sector.copy}</p>
                      <a
                        href={`/solicitar-servicio?sector=${sector.slug}`}
                        className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-[#173aab] transition hover:gap-3"
                      >
                        Solicitar servicio para {sector.title.toLowerCase()} <ArrowRight size={16} aria-hidden="true" />
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}

// premium_work_nuxt/app/components/SectorsAccordion.vue
<template>
  <section :aria-label="t('sectors.aria')" class="relative overflow-hidden bg-white py-10 md:py-16">
    <div aria-hidden="true" class="hero-dots pointer-events-none absolute inset-0" />
    <div class="relative z-10 mx-auto grid w-full max-w-[1600px] gap-6 px-5 md:gap-12 md:px-8 lg:grid-cols-[1fr_1.5fr] lg:gap-24 lg:px-10">
      <div class="lg:sticky lg:top-28 lg:self-start">
        <p class="eyebrow flex items-center gap-2 text-[#131313]/60">
          <span class="text-[#eab308]" aria-hidden="true">◆</span> {{ t("sectors.eyebrow") }}
        </p>
        <h2 class="display mt-4 text-3xl leading-[1.02] text-[#131313] md:mt-6 md:text-[clamp(2.5rem,5vw,4.5rem)]">
          {{ t("sectors.titleA") }}<br />{{ t("sectors.titleB") }}
        </h2>
        <p class="mt-6 hidden max-w-md text-base leading-7 text-[#131313]/70 md:block">
          {{ t("sectors.copy") }}
        </p>
        <a
          href="/solicitar-servicio"
          class="mt-6 inline-flex items-center gap-2 rounded-full bg-[#2451e6] px-6 py-3.5 text-sm font-bold text-white transition hover:-translate-y-0.5 hover:bg-[#1b45c4] md:mt-8"
        >
          {{ t("sectors.cta") }}
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M5 12h14"/><path d="m12 5 7 7-7 7"/></svg>
        </a>
      </div>

      <div class="border-t border-[#131313]/15">
        <div v-for="(sector, index) in sectors" :key="sector.slug" class="border-b border-[#131313]/15">
          <button
            type="button"
            :aria-expanded="open === index"
            :aria-controls="`sector-panel-${sector.slug}`"
            class="group flex w-full items-center justify-between gap-6 py-3 text-left md:py-4"
            @click="open = open === index ? null : index"
          >
            <span
              class="display text-xl transition-colors md:text-[1.75rem]"
              :class="open === index ? 'text-[#173aab]' : 'text-[#131313] group-hover:text-[#173aab]'"
            >
              {{ sector.title }}
            </span>
            <span
              class="flex size-9 shrink-0 items-center justify-center rounded-full border transition-all md:size-10"
              :class="open === index ? 'rotate-180 border-[#2451e6] bg-[#2451e6] text-white' : 'border-[#131313]/25 text-[#131313]/70 group-hover:border-[#173aab]/60'"
            >
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m6 9 6 6 6-6"/></svg>
            </span>
          </button>
          <div
            :id="`sector-panel-${sector.slug}`"
            role="region"
            class="grid transition-[grid-template-rows] duration-300 ease-out"
            :class="open === index ? '[grid-template-rows:1fr]' : '[grid-template-rows:0fr]'"
          >
            <div class="overflow-hidden">
              <div class="pb-7 pr-4 md:pr-16">
                <p class="max-w-xl text-base leading-7 text-[#131313]/70">{{ sector.copy }}</p>
                <a
                  :href="`/solicitar-servicio?sector=${sector.slug}`"
                  class="mt-4 inline-flex items-center gap-2 text-sm font-bold text-[#173aab] transition hover:gap-3"
                >
                  {{ t("sectors.requestFor") }} {{ sector.title.toLowerCase() }}
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M5 12h14"/><path d="m12 5 7 7-7 7"/></svg>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { ref } from "vue";

const { t, dict } = useLang();

const SLUGS = ["hoteles", "restaurantes", "catering", "eventos-corporativos", "eventos-deportivos", "festivales", "bodas-y-celebraciones", "experiencias-privadas"];
const sectors = dict.value.sectors.items.map((s, i) => ({ ...s, slug: SLUGS[i] ?? `sector-${i}` }));

const open = ref<number | null>(0);
</script>
